apiVersion: v1
kind: ServiceAccount
metadata:
  name: hangang
  labels:
    app.kubernetes.io/name: hangang
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hangang-controller
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]
  # Required only when --kubernetes-tls is enabled.
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  # Used only when --kubernetes-publish-address is configured.
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hangang-controller
subjects:
  - kind: ServiceAccount
    name: hangang
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hangang-controller
